name: Unit Tests
on:
  push:
  pull_request:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python test/unit/test_math_lib.py
  run_functional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash test/func/test_add.sh